git:
  depth: 1  
branches:
  only:
    - master
    - gh-pages
language: java
jdk:
- oraclejdk7

script: ./script.sh

env:
  global:
    secure: Ie78jVXdvkTTxZ/gDoSl44EFixI5BIJ4SPikyn5VsI/Pqk6A9577sPJUgrwgVGocWVTTYI4Lqxfid8dnNV1XIiZjDb/BX509wiAFPngB0ONH1chicvlAc3R/Nwg25ImdCuoQqhwjqYhyezsphLKzAsLi+/Vvdsz5+EsOnqKYMDg=
